version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - orderflow-net

  produto-service:
    build:
      context: ./servico-produto
    container_name: produto-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
    networks:
      - orderflow-net

  usuario-service:
    build:
      context: ./servico-usuario
    container_name: usuario-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    networks:
      - orderflow-net

  pedido-service:
    build:
      context: ./servico-pedido
    container_name: pedido-service
    ports:
      - "8083:8083"
    depends_on:
      - rabbitmq
    networks:
      - orderflow-net

networks:
  orderflow-net:
    driver: bridge
